### PR TITLE
task: support PHP 8.3

### PR DESCRIPTION
**Pull request by cngJo**
I installed it locally with `--ignore-platform-reqs` in a PHP 8.3 project and didn't notice any issues.

Let's see what the tests say 😉

Thanks for the Bundle!

### CODE REVIEW

**Review by mike4git — APPROVED** [review]
I'm fine with it - thx for your PR

**Comment by jdreesen** [comment]
I think we first need to allow PHP 8.3 in `teamneusta/pimcore-testing-framework` for the tests to pass.

**Comment by jdreesen** [comment]
No, we're not currently working on it. If you want to create a PR, please target the `v0.12` branch, as `main` currently contains some changes that are not yet ready to be released.

**Comment by lukadschaak** [comment]
I started a merge request on the testing framework.

As soon as this is merged and released i will update this one here as well.

**Comment by jdreesen** [comment]
[teamneusta/pimcore-testing-framework `v0.12.8`](https://github.com/teamneusta/pimcore-testing-framework/releases/tag/v0.12.8) with support for PHP 8.3 has just been relesed.

**Comment by lukadschaak** [comment]
Done https://github.com/teamneusta/pimcore-fixture-bundle/releases/tag/2.2.0

**Comment by cngJo** [comment]
Awesome, thank you guys! 🎉 🚀

**Pull request merged**
